### ISSUE TITLE
Support for bookmarkable URL for reports.

### ISSUE THREAD

**Issue by mysticfall** [mysticfall/pivot4j#117]
Add support for the bookmarkable URLs for each reports. And we can add someway to provide EL context variables for additional request parameters as well (see #37)

**Comment by ravindragullapalli** [comment]
What if we have to pass multiple parameters? For example if I have to filter with age 25 and 26 or age range 25 to 30, how can I do that?

**Comment by mysticfall** [comment]
@ravindragullapalli You can just define the parameter multiple times with different values (i.e. `?age=25&age=26`) and expect the parameter value to be `java.util.List`.

Sorry for the very late response.
