### ISSUE TITLE
Update to PrimeFaces 5.1+

### ISSUE THREAD

**Issue by VsevolodGolovanov** [mysticfall/pivot4j#178]
Since PF 5.1 a lot of old chart classes were removed. Thus analytics is not as good a starting point as it used to be for building Pivot4J UI with PF.

**Comment by mysticfall** [comment]
Currently, I'm too much occupied with other open source projects which I'm maintaining. I hope I could spare enough time for this sometime next week.

Thanks for the report!

**Comment by mysticfall** [comment]
Fixed with 0b1b555adb97c2fd6312207c79d74cfb121ff222. Thanks for your patience!
