### ISSUE TITLE
pivot4j-core compile failed!

### ISSUE THREAD

**Issue by nangzi** [mysticfall/pivot4j#189]
I compile the pivot4j-core project, and found 
![image](https://cloud.githubusercontent.com/assets/5505802/8696241/5683f8e4-2b1d-11e5-9839-41e04a5b0f75.png)
The source code didn't have the **CupParser** class, I found the file in the main site's download jar.
But it still has error, How could I solve this.
@mysticfall ,Thank you.

**Comment by mysticfall** [comment]
Hi,

The ```CupParser``` class is generated during the build process, so if you build your project with Maven, you should be able to compile it without a problem.

If you need further assistance regarding setting up the project for development, please let me know.

**Comment by nangzi** [comment]
Hi.

I recompiled the project, it correct. 
Thanks again, Awesome project!
