### ISSUE TITLE
Using datasources from config file in pentaho-plugin

### ISSUE THREAD

**Issue by pronchakov** [mysticfall/pivot4j#191]
Hello.

Is there a way to use datasources from pivot4j-config.xml rather than pentaho datasources in pivot4j pentaho-plugin?
Just like it works in standalone pivot4j...

I've tried to add `<datasources> ` element to pivot4j-config.xml inside pentaho-solutions/...../ but it didn't worked.

Thank you.

**Comment by pronchakov** [comment]
I've switched from
```
<managed-bean xmlns:faces-config="http://java.sun.com/xml/ns/javaee">
    <managed-bean-name>dataSourceManager</managed-bean-name>
    <managed-bean-class>org.pivot4j.pentaho.datasource.PentahoDataSourceManager</managed-bean-class>
    <managed-bean-scope>session</managed-bean-scope>
</managed-bean>
```
to
```
<managed-bean xmlns:faces-config="http://java.sun.com/xml/ns/javaee">
    <managed-bean-name>dataSourceManager</managed-bean-name>
    <managed-bean-class>org.pivot4j.analytics.datasource.simple.SimpleDataSourceManager</managed-bean-class>
    <managed-bean-scope>session</managed-bean-scope>
    <managed-property>
        <property-name>settings</property-name>
        <value>#{settings}</value>
    </managed-property>
</managed-bean>
```
in ```pentaho-solutions/system/pivot4j/webapp/WEB-INF/faces-config.xml```

and it worked. Now I can use datasources from pivot4j-config.xml

But the question is: wouldn't it affect on any another functionality?

**Comment by mysticfall** [comment]
I tried to minimize the differences between the standalone and plugin version to ease maintenance cost.

So, chances are that it would work without any problem if you just replace the Pentaho specific data source manager with the default implementation.

Please let me know if you find anything not working with that configuration.

Sorry for the very late response!

**Comment by pronchakov** [comment]
No, the bean configuration replacement with SimpleDataSourceManager, as I mentioned in previous post, works ok. No problems were discovered so far.
