### ISSUE TITLE
Issue in drill-down and roll-up with Parent-Child Hierarchies

### ISSUE THREAD

**Issue by ravindragullapalli** [mysticfall/pivot4j#194]
I am trying to design pivot4j report with an example of Parent-Child hierarchy explained in  http://inquidia.com/news-and-info/parent-child-hierarchies-abnormal-genealogy

I created cube and in pivot4j when I display the data it is showing properly in expanded mode.

However, when I collapse a node the node completely gets disappeared.

**Comment by mysticfall** [comment]
Hi, 

Can you try to reproduce the issue with the FoodMart database? Please understand that it's really hard to pin down such a problem without being able to reproduce the issue locally.

The `Employee` dimension has the parent-child association with itself, so I suppose the problem should manifest using that dimension, if it's inherent in the way Pivot4J handles such a relationship.

Please let me know if you can find anything. Thanks!

**Comment by ravindragullapalli** [comment]
Hi,

I redesigned the schema and it is working properly now. 

I think it is the issue with the schema design. Closing this bug.
