### ISSUE TITLE
opacity stay on 0.75 when cube structure and pivot structure 's split drag

### ISSUE THREAD

**Issue by mariogaitan** [mysticfall/pivot4j#199]
When a user wants to expand the cube structure and drag the split to do it, some efect's class stay in cube structure, I fixed changing view.xhtml

					<p:droppable for="cube-navigator"
						hoverStyleClass="ui-widget-header" tolerance="pointer">
						<p:ajax listener="#{navigatorHandler.onDrop}"
							update=":source-tree-form,:target-tree-form,:toolbar-form,:grid-form,:editor-form:mdx-editor,:editor-form:editor-toolbar"
							oncomplete="onViewChanged()" />
					</p:droppable>

I changed this property hoverStyleClass="ui-widget-header", and I added a class like that:

.fix-for-opacity {
	opacity: 1 !important;
}

Maybe this is a primefaces's bug...

**Comment by mysticfall** [comment]
I found some visual glitches regarding drag & drop operation with the recent version. So I just updated the PrimeFaces to 3.5 version to fix it along with this issue.

Please try the latest snapshot and let me know if the problem still persists. Thanks!
