### ISSUE TITLE
Can't see the enlarged screenshots image on the pivot4j homepage.

### ISSUE THREAD

**Issue by eunsucking** [mysticfall/pivot4j#215]
Hi.
I can't see the enlarged screenshots image on http://www.pivot4j.org/analytics.html
When I click the screenshot image, The page just turns black like the image below. 

![default](https://user-images.githubusercontent.com/27847712/28004482-edba6268-657f-11e7-8c2a-3825f3177299.PNG)

Is it OK report this issue here? I can't find other Issue pages about pivot4j homepage.
This issue has been shown in the following browser versions.

**Chrome : 59.0.3071.115 (latest version on 2017/07/10)
IE : 11.0.9600.18697**

This is the result of my research.

**_1. After the each image has been clicked, All image files are loaded at Chorme Developertools._** 
screenshot-main-thumb.png → this is loaded
screenshot-main.png → this is also loaded

![default](https://user-images.githubusercontent.com/27847712/28008726-ad029aa6-6593-11e7-88ce-c14f0aee6701.PNG)

**_2.Both absolute paths are accessible._**
http://www.pivot4j.org/img/screenshot-main.png
http://www.pivot4j.org/img/screenshot-main-thumb.png
→ Both can see images.

**_3.Images are specified as a relative path like below._**
`<a href="./img/screenshot-main.png" rel="lightbox[page]">`
`<img src="./img/screenshot-main-thumb.png" alt="Main Window" /></a>`

**_4.`data-lightbox` attribute is not defined in a tag_**

On the official website of lightbox, It is recommended to initialize with HTML like this.

##################################################################
Initialize with HTML(http://lokeshdhakar.com/projects/lightbox2/#getting-started)

Add a data-lightbox attribute to any image link to enable Lightbox. For the value of the attribute, use a unique name for each image. For example:
`<a href="images/image-1.jpg" data-lightbox="image-1" data-title="My caption">Image #1</a>`

Optional: Add a data-title attribute if you want to show a caption.
##################################################################

But pivot4j's html is like this. `data-lightbox` attribute is not defined in a tag.
```
<a href="http://www.pivot4j.org/img/screenshot-main.png" rel="lightbox[page]">
	<img src="./img/screenshot-main-thumb.png" alt="Main Window">
</a>
```

**Comment by mysticfall** [comment]
It turns out that there was an issue with the Maven skin the project uses, so I just updated it to the latest version to fix it: https://github.com/andriusvelykis/reflow-maven-skin/issues/35

Thanks much for the detailed report :)
